Feature/handlers
s21platform/optionhub-service pull request #12
Opened 2024-09-06 14:37 UTC by meeeeeeeeh

GetOsById and AddOs added

2024-09-06 21:42 UTC, alexseipopov requested changes

2024-09-06 21:42 UTC, alexseipopov commented on internal/repository/db/interface.go
> +package db
Есть предложение называть такие файлики contract.go. Сейчас почти в каждом проекте мы используем этот нейминг, чтобы не путаться)

2024-09-06 21:42 UTC, alexseipopov commented on internal/service/service.go
> +		return nil, fmt.Errorf("cannot add new os, err: %v", err)
в этих местах: 22, 30 - строках давай ошибку возвращать в gRPC формате, например: **status**.Errorf(**codes**.FailedPrecondition, "Вы не являетесь участником s21")
status и codes - это библиотеки, вроде даже не требующие доп установки

2024-09-07 16:31 UTC, alexseipopov commented on internal/service/service.go
> +	db db.DbRepo
dbR

2024-09-07 16:32 UTC, alexseipopov commented on internal/service/service.go
> +type service struct {
перенести контракт в service

2024-09-09 09:22 UTC, dreamcoiI requested changes

2024-09-09 09:22 UTC, dreamcoiI commented on internal/service/service.go
> +type service struct {
Так же не очень понятно, почему service приватная структура

2024-09-12 21:54 UTC, alexseipopov requested changes

2024-09-12 21:54 UTC, alexseipopov commented on cmd/service/main.go
> +	opionhubService := service.NewService(dbRepo)
op**T**ion...

2024-09-12 21:54 UTC, alexseipopov commented on cmd/service/main.go
>  	defer dbRepo.Close()
Это лучше унести на 21 строку. Тут от дефера уже мало толку

2024-09-15 12:03 UTC, dreamcoiI commented
@alexseipopov дай права на апрув

2024-09-15 12:03 UTC, dreamcoiI submitted a review, later dismissed

2024-09-18 18:29 UTC, alexseipopov approved these changes

2024-09-19 06:06 UTC, merged