Feature/name search
s21platform/optionhub-service pull request #13
Opened 2024-09-28 16:11 UTC by meeeeeeeeh

2024-09-28 16:35 UTC, alexseipopov requested changes

2024-09-28 16:35 UTC, alexseipopov commented on internal/repository/db/repository.go
> +	optionhub_proto "github.com/s21platform/optionhub-proto/optionhub-proto"
Тут по линтингу луше не использовать нижнее подчеркивание, лучше просто optionhubproto

2024-09-28 16:35 UTC, alexseipopov commented on internal/repository/db/repository.go
> +func (r *Repository) GetOsBSearchName(ctx context.Context, name string) (*optionhub_proto.GetByNameOut, error) {
тут буква пропущена) GetOSb**y**SearchName

2024-09-28 16:35 UTC, alexseipopov commented on internal/repository/db/repository.go
> +func (r *Repository) GetOsBSearchName(ctx context.Context, name string) (*optionhub_proto.GetByNameOut, error) {
тут еще архитектурный момент есть, я сейчас про это читаю и кажется лучше сделать модельки отдельные свои, и тут работать с ними, а переводить в протовсие структуры на стороне сервисного слоя. НО!!! это на твое усмотрение, хочешь ли ты сделать это в рамках этой задачи или можем сделать отдельную. Я сейчас стараюсь во всех сервисах достигнуть единства архитектуры, это все равно не быстро, так что не горит делать в рамках этого ПР

2024-09-28 16:35 UTC, alexseipopov commented on internal/service/contract.go
> +	optionhub_proto "github.com/s21platform/optionhub-proto/optionhub-proto"
тут так же без нижнего подчеркивания

2024-09-29 11:49 UTC, meeeeeeeeh commented on internal/repository/db/repository.go
> +func (r *Repository) GetOsBSearchName(ctx context.Context, name string) (*optionhub_proto.GetByNameOut, error) {
Я сейчас поправила. Все равно это как раз только для нвой ручки нужно было сделать

2024-09-29 11:52 UTC, alexseipopov requested changes

2024-09-29 11:52 UTC, alexseipopov commented on internal/service/service.go
> +	for idx := range os {
Предлагаю тут испльзовать подход с извлечением самого объекта, нежели по индексу. по типу тут _, osObj := range os, а ниже собственно извлекать osObj.Id и osObj.Name

2024-09-29 12:59 UTC, alexseipopov approved these changes

2024-09-29 13:48 UTC, merged