add new handles
s21platform/optionhub-service pull request #22
Opened 2024-11-27 13:42 UTC by Snegov1k

2024-11-27 18:26 UTC, dreamcoiI commented
укажи дексрипшн+ номер таски

2024-11-27 19:09 UTC, Snegov1k commented
Добавил ручки по направлениям: workplace, study place, hobby, skill, city
В каждом направлении по три ручки: 
    1) поиск по имени (включает в себя кейс < 2 символов в имени)
    2) поиск по id
    3) добавление

Добавил методы в слой бд для работы ручек
Добавил миграции по направлениям

Номера таски нет

2024-11-27 19:10 UTC, Snegov1k commented
В последующих пр дескрипшн брать из таски?

2024-11-29 20:46 UTC, alexseipopov requested changes

2024-11-29 20:46 UTC, alexseipopov commented on internal/model/categories.go
> +		result = append(result, avatar.ToProto())
Миш, вот тут заметил, видимо это Сишная привычка, в гошке не так часто выносят хелпер функции. тут можно прям внутри поставить, читаемость улучшится, лишний раз не надо бегать и искать что откуда. В аватаре видил такие же - если что не выноси). И тут давай прям тут вместо функции сразу структуру аппендить)

2024-12-04 19:18 UTC, alexseipopov approved these changes

2024-12-04 19:39 UTC, merged